# Site wide configuration

title: "Il mio sito"
description: "Questa è la descrizione del mio fantastico sito DnD"
tagline: Breve descrizione del sito che ne spiega lo scopo in poche parole.
logo: logo.png # 120x120 px default image used for Twitter summary card
teaser: teaser.png # 400x250 px default teaser image used in image archive grid
locale: it
url: https://coopnovaglia.github.io/jekyll-theme-skinny-bones
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Nome Cognome
  email: email@example.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
